@startuml
'https://plantuml.com/sequence-diagram

autonumber

Person -> HelloController: onAddButton()
HelloController --> HelloController: checks if it is task or project
HelloController --> HelloController: addTask(name)
HelloController -> GuiView: confirmTaskWithoutDescription()
GuiView -> Person: Confirmation Dialog
HelloController -> GuiView: addTaskTitledPane(...)
Task <- HelloController : taskToAdd = new Task(...)
HelloController -> Project: listOfTask.add(task);
GuiView -> Person: add Task Title Pane to right Project Titled Pane
HelloController -> Person : All fields are cleared
@enduml