@startuml
'https://plantuml.com/sequence-diagram

autonumber

Person -> HelloController: onAddButton()
HelloController --> HelloController: checks if it is task or project
HelloController -> HelloController: addTask(name)
HelloController -> HelloController: confirmTaskWithoutDescription()

Task <- HelloController : taskToAdd = new Task(...)
HelloController -> HelloController: newTaskTitledPane(...)
HelloController -> Project: listOfTask.add(task);
HelloController -> Person: add Task Title Pane to right Project Titled Pane
HelloController -> Person : All fields are cleared
@enduml